// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $AddToCartButton_vtex from "./islands/AddToCartButton/vtex.tsx";
import * as $FilterPriceRange from "./islands/FilterPriceRange.tsx";
import * as $Filters from "./islands/Filters.tsx";
import * as $Form from "./islands/Form.tsx";
import * as $IframeLogin from "./islands/IframeLogin.tsx";
import * as $Menu from "./islands/Menu.tsx";
import * as $MultiRangeSlider from "./islands/MultiRangeSlider.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/AddToCartButton/vtex.tsx": $AddToCartButton_vtex,
    "./islands/FilterPriceRange.tsx": $FilterPriceRange,
    "./islands/Filters.tsx": $Filters,
    "./islands/Form.tsx": $Form,
    "./islands/IframeLogin.tsx": $IframeLogin,
    "./islands/Menu.tsx": $Menu,
    "./islands/MultiRangeSlider.tsx": $MultiRangeSlider,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
